# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Doctors' Blog"
email: benjamin@doc.tors.life
description: > # this means to ignore newlines until "baseurl:"
            "Doctors' blog is a site where I (Doctors) talk about anything
            that I feel relevant to share, wanted or not. Stuff I might 
            post include stuff such as books, tech, science, really 
            just anything that I think is intresting."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://doc.tors.life/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: TheDoctors_Life
github_username:  Coding-Doctors

# Build settings
permalink: "/:short_year/:month/:day/:title"
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-include-cache
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.md
